import type { Metadata } from 'next'
import { Poppins, Josefin_Sans } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
	variable: '--poppins',
	subsets: ['latin'],
	weight: ['300', '400'],
})

const josefinSans = Josefin_Sans({
	variable: '--josefin-sans',
	subsets: ['latin'],
	weight: ['300', '400'],
})

export const metadata: Metadata = {
	title: 'Ixlos Kurslari',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${poppins.variable} ${josefinSans.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	)
}
